### PR TITLE
Segmentation fault on resize empty window.

### LINKED ISSUE #198: Segmentation fault on resize empty window.
Segmentation fault on next simple code:
~~~
int main(void)
{
    LCUI_Init();
    LCUIDisplay_SetSize(320, 239);
    return LCUI_Main();
}
~~~

1. Compile example above.
2. Launch it.

Environment:
- LCUI version: 1.3.0
- Build tools: gcc 8.3.0
- OS and version: Ubuntu 18.10

Reason of crash:

 - in commit https://github.com/lc-soft/LCUI/commit/13c84b2a6a317a79113c6314aca17f2130921b63 used default prototype by default, that have non-empty paint handler pointer (NULL used by default for proto before this fix).

 - with default protoype for all widgets function src/gui/widget_paint.c:Widget_IsPaintable() returns true.

 - that is why in render function return non-zero count for empty window, cause src/gui/widget_paint.c:WidgetRenderer() function setup that->can_render_self = Widget_IsPaintable(w) always true.

p.s. but, if use LCUIDisplay_SetSize(321, 241) in example, it is not crashed, couse it updates correctly and creates surface->pixmap and surface->gc and empty widget render successfully

### PR DESCRIPTION
**Pull request by vbalyasnyy**
Fixes #198 .

I'm not sure that it is best fix for this problem, but we need some way to check for default prototype.

@lc-soft

### CODE REVIEW

File: src/gui/widget_paint.c [hunk 1]
```diff
@@ -122,7 +122,7 @@ static LCUI_BOOL Widget_IsPaintable(LCUI_Widget w)
 	    s->shadow.spread > 0) {
 		return TRUE;
 	}
-	return w->proto && w->proto->paint;
+	return w->proto && w->proto->paint && w->proto->name;
```
Comment (lc-soft) [inline src/gui/widget_paint.c]: The condition is that the widget has a custom paint method, so just check to see if the widget's paint method is equal to the default paint method.

```diff
+ static LCUI_WidgetPrototype default_proto = NULL;
+
+ if (!default_proto) {
+         default_proto = LCUIWidget_GetPrototype(NULL);
+ }
- return w->proto && w->proto->paint && w->proto->name;
+ return w->proto->paint != default_proto->paint;
```

Comment (lc-soft) [reply src/gui/widget_paint.c]: The `default_proto` variable can be moved into the `self` structure.

```diff
static struct LCUI_WidgetRenderModule {
	LCUI_BOOL active;
+ 	LCUI_WidgetPrototype default_proto;
	RBTree groups;
	LinkedList rects;
} self = { 0 };
```

So, we don't have to check whether default_proto is NULL here,

```diff
void LCUIWidget_InitRenderer(void)
{
	RBTree_Init(&self.groups);
	RBTree_OnCompare(&self.groups, OnCompareGroup);
	RBTree_OnDestroy(&self.groups, OnDestroyGroup);
	LinkedList_Init(&self.rects);
+	self.default_proto = LCUIWidget_GetPrototype(NULL);
	self.active = TRUE;
}
```

Comment (vbalyasnyy) [reply src/gui/widget_paint.c]: return w->proto->paint && proto->paint != default_proto->paint;

maybe we should check for correct proto->paint handler yet, in future it would be availability be creates abstract prototypes without paint hander
